// The art's contract with the game: one world per ladder rung, and every world's files in the shapes
// and sizes the renderer draws them at. These files are generated by the scripts in art/marrow/.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import worlds from '../assets/worlds.json' with { type: 'json' };
import palette from '../assets/palette.json' with { type: 'json' };
import maw from '../assets/maw.json' with { type: 'json' };
import { LADDER } from '../src/ai.js';

const ASSETS = new URL('../assets/', import.meta.url);
const BASES = ['C', 'B1', 'B2', 'V'];
const HEX = /^#[0-9a-f]{6}$/;
const json = (rel) => JSON.parse(readFileSync(new URL(rel, ASSETS), 'utf8'));
const size = (rel) => { // a PNG's width and height, from its header
  const b = readFileSync(new URL(rel, ASSETS));
  return [b.readUInt32BE(16), b.readUInt32BE(20)];
};

test('each ladder opponent fights in its own world: the Rusher in the cathedral, the Waiter at dusk, the Shifter in the abyss', () => {
  assert.equal(worlds.order.length, LADDER.length);
  assert.deepEqual(Object.fromEntries(LADDER.map((p, rung) => [p, worlds.order[rung]])), { rusher: 'cathedral', waiter: 'dusk', shifter: 'abyss' });
});

test('every world has a scene for each screen base, with whole-pixel detail anchors, plus its colors', () => {
  for (const name of worlds.order) {
    const scenes = json(`${name}/scenes.json`);
    assert.deepEqual(Object.keys(scenes).sort(), ['B1', 'B2', 'C', 'V', 'colors'], name);
    for (const base of BASES) {
      for (const [x, y] of scenes[base].vessels) assert.ok(Number.isInteger(x) && Number.isInteger(y), `${name} ${base} vessel ${x},${y}`);
      for (const [x, y, floorY] of scenes[base].drips) assert.ok(Number.isInteger(x) && y < floorY, `${name} ${base} drip ${x},${y}`);
    }
    const c = scenes.colors;
    assert.deepEqual(Object.keys(c.hud).sort(), ['dim', 'mark', 'markEnd', 'markHere', 'text'], name);
    for (const hex of [...c.vessel, c.drip, c.spore, c.clear, ...Object.values(c.hud)]) assert.match(hex, HEX, name);
    assert.ok(c.sporeAlpha > 0 && c.sporeAlpha < 1, name);
  }
});

test("every world's images have the sizes the game draws them at; the far layer is an 800 px panorama", () => {
  for (const name of worlds.order) {
    assert.deepEqual(size(`${name}/far.png`), [800, 180], name);
    assert.deepEqual(size(`${name}/fog.png`), [320, 180], name);
    for (const base of BASES) assert.deepEqual(size(`${name}/scene-${base}.png`), [320, 180], `${name} ${base}`);
    assert.deepEqual(size(`${name}/maw.png`), [maw.frame[0] * maw.frames, maw.frame[1]], name);
  }
});

test('palette.json has the bone blade colors, and each fighter bleeds its own glow', () => {
  assert.deepEqual(Object.keys(palette.blade).sort(), ['body', 'hilt', 'tip']);
  for (const hex of Object.values(palette.blade)) {
    assert.match(hex, HEX);
    assert.ok(!palette.amber.includes(hex) && !palette.cyan.includes(hex), `${hex} would be palette-swapped`);
  }
  assert.deepEqual(palette.ichor, [palette.amber.slice(1), palette.cyan.slice(1)]);
});
